### ISSUE TITLE
Documentation for external dependencies

### ISSUE THREAD

**Issue by giffsapros** [fonsleenaars/tqdb#35]
Would it be possible to update the documentation and/or source code of what's needed in order to get the parser to run correctly?

When I pull code from the branch and execute run.py, the parser finishes parsing skills and affixes correctly, but as soon as it attempts to parse "weapons, jewelry and armor", I get repeated TextureViewer.exe crashes, even though the Texture Viewer application itself seems to work fine if I try to extract textures manually.

I've checked the Windows Logs to see whether anything useful is logged in the system event logs for the TextureViewer crashes, though the logs don't seem very useful - happy to post samples if you think that will help.

Additionally, I'm also getting errors when trying to parse just "skills", which look like they're happening because I have incompatible versions of some core libraries installed. Any documentation of which versions of the libraries are being used here, or instructions on getting this to run from a clean Python install would be helpful.

run.py -c skills
Determining what files are required...
Parsing skills                                [####################] DONE
Writing output to files...
Traceback (most recent call last):
  File "E:\Python\Anaconda\lib\site-packages\PIL\ImageFile.py", line 482, in _sa
ve
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:
  File "E:\Python\Anaconda\lib\site-packages\PIL\Image.py", line 1930, in save
    save_handler(self, fp, filename)
  File "E:\Python\Anaconda\lib\site-packages\PIL\PngImagePlugin.py", line 821, i
n _save
    [("zip", (0, 0)+im.size, 0, rawmode)])
  File "E:\Python\Anaconda\lib\site-packages\PIL\ImageFile.py", line 490, in _sa
ve
    e.setimage(im.im, b)
SystemError: tile cannot extend outside image

**Comment by fonsleenaars** [comment]
Absolutely, this code base has been through a few iterations and most of it was in the "as long as the output is correct - whatever" mentality.

I know I ran into some issues a little while ago when Windows 10 installed a service pack, apparently the old files (TextureViewer included) relies on some ancient DLL that is no longer available by default.

I'll get to documentation after I finally finish up this current milestone. Thanks for the report.

**Comment by fonsleenaars** [comment]
@giffsapros only took me 8 years 😅 The Windows tools are gone. Everything now builds and runs in a container (Rust for reading the game files, Python for the parser), and the README and docs/setup.md walk through the whole thing.
